// use '|' so that 'A' < 'a' < '|' (charCode)
const HOMOZYGOUS_DOMINANT = 'AA';
const HETEROZYGOUS = 'Aa';
const HOMOZYGOUS_RECESSIVE = 'aa';
const HEMIZYGOUS_DOMINANT = 'A|';
const HEMIZYGOUS_RECESSIVE = 'a|';

const AUTOSOMAL = [HOMOZYGOUS_DOMINANT, HETEROZYGOUS, HOMOZYGOUS_RECESSIVE];
const X_FEMALE = AUTOSOMAL;
const X_MALE = [HEMIZYGOUS_DOMINANT, HEMIZYGOUS_RECESSIVE];
const DOMINANT = [HOMOZYGOUS_DOMINANT, HETEROZYGOUS, HEMIZYGOUS_DOMINANT];
const RECESSIVE = [HOMOZYGOUS_RECESSIVE, HEMIZYGOUS_RECESSIVE];

module.exports = {
  HOMOZYGOUS_DOMINANT,
  HETEROZYGOUS,
  HOMOZYGOUS_RECESSIVE,
  HEMIZYGOUS_DOMINANT,
  HEMIZYGOUS_RECESSIVE,
  AUTOSOMAL,
  X_FEMALE,
  X_MALE,
  DOMINANT,
  RECESSIVE,
};
  isValid: isGenotypeValid,
